### ISSUE TITLE
☂️ Test-app improvements

### ISSUE THREAD

**Issue by mayank99** [iTwin/stratakit#72]
The [test app](https://github.com/iTwin/kiwi/tree/main/apps/test-app) can be improved in several ways.

- [x] ~~[Playwright tags](https://playwright.dev/docs/test-annotations#tag-tests) can be used to annotate `@visual` and `@a11y` tests for easy cross-component filtering.~~ Done in #74
- [x] ~~Test pages could expose some UI to easily set URL searchparams.~~ Done in #394.
- [x] ~~Dockerfile could be improved to *not* run `build` each time. Can we just use the build from host machine?~~ Done in #627
- [x] ~[Sharding](https://playwright.dev/docs/test-sharding) can be used to speed up CI runs.~ Done in #346.
- [ ] A [reporter](https://playwright.dev/docs/test-reporters#github-actions-annotations) can be used to add annotations in PRs.
  - Investigated in [#346](https://github.com/iTwin/kiwi/pull/346) but removed the `"github"` reporter since it could lead to duplicate annotations when sharding ([#346 (comment)](https://github.com/iTwin/kiwi/pull/346#discussion_r1943235569)).
- [ ] Visual test images can be improved. Components are sometimes too small, and the test images are too wide.
- [ ] Directory nesting could be reduced.
     - e.g. `/apps/test-app/app/routes/tests/checkbox/index.spec.ts` → `/test-app/tests/anchor/spec.ts`.
     - This is now unblocked after #189 
     - Needs a bit of discussion because there are tradeoffs with reducing nesting.
- [x] ~~The version of `test-app` deployed on github-pages does not allow visiting nested routes directly (it works with client-side navigation only). [Prerendering](https://github.com/remix-run/react-router/blob/dev/docs/how-to/pre-rendering.md) (or a workaround for gh-pages) could be utilized to improve this experience.~~ Done in #156.
- [x] ~~An abstraction can be created on top of `useSearchParams` to make it easier to read query-params.~~ Done in #166.
